{"timestamp":"2025-10-27T15:11:02.398133Z","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-27T15:11:02.400408Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/test_http_connection_dag.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-27T15:11:02.657554Z","level":"info","event":"[DEBUG] Base URL from Airflow connection:","logger":"task.stdout"}
{"timestamp":"2025-10-27T15:11:07.479263Z","level":"error","event":"HTTP error: ","logger":"airflow.task.hooks.airflow.providers.http.hooks.http.HttpHook","filename":"http.py","lineno":314}
{"timestamp":"2025-10-27T15:11:07.479662Z","level":"error","event":"{\"timestamp\":\"2025-10-27T15:11:07.190+00:00\",\"status\":404,\"error\":\"Not Found\",\"path\":\"/\"}","logger":"airflow.task.hooks.airflow.providers.http.hooks.http.HttpHook","filename":"http.py","lineno":315}
{"timestamp":"2025-10-27T15:11:07.480082Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":972,"error_detail":[{"exc_type":"AirflowException","exc_value":"404:","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/test_http_connection_dag.py","lineno":20,"name":"test_http_connectivity"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py","lineno":301,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py","lineno":352,"name":"run_and_check"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py","lineno":316,"name":"check_response"}],"is_group":false,"exceptions":[]},{"exc_type":"HTTPError","exc_value":"404 Client Error:  for url: http://host.docker.internal:8082/","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py","lineno":312,"name":"check_response"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/models.py","lineno":1026,"name":"raise_for_status"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-27T15:11:07.504362Z","level":"info","event":"[ERROR] Failed to connect: 404:","logger":"task.stdout"}
